//let faveSongs = [
//   "Song1 - I am What I am",
//   "Song2 - Better the Devil you Know",
//   "Song3 - What the F*ck is Wrong with you"
//];
//faveSongs.push("Song4 - Fish");
//faveSongs.pop();
//console.log(faveSongs)

//pop & push
/*
let faveSites = [
    "pornHub",
    "watchCartoons",
    "netFlix"
    ];
faveSites.push("gamesWorkshop");
faveSites.push("wikipedia")
faveSites.pop()
console.log(faveSites)
*/

//shift
/*
let faveSites = [
    "pornHub",
    "watchCartoons",
    "netFlix"
   ];
let firstElement = faveSites.shift();
console.log (faveSites)
*/

//unshift
/*
let faveSites = [
    "pornHub",
    "watchCartoons",
    "netFlix"
   ];
let firstElement = faveSites.unshift("gamesWorkshop", "3Store");
console.log (faveSites)
*/